"""
TUF 谱面查询命令（完整版）
- /~tufsearch <关键词> [页码]  搜索谱面（截图发送，带编号）
- /~tufd [编号]                下载搜索结果中的谱面
- /~tufpage [页码]              搜索结果翻页
- /~tuflevel <歌曲名|关卡ID>    查询谱面详情（卡片图片）
- /~tuf谱面 <歌曲名|关卡ID>    同上（中文别名）
"""

from __future__ import annotations

import asyncio
import base64
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

import httpx

from core.logger import get_logger
from core.config import get_config

logger = get_logger("tuf_commands")

# ══════════════════════════════════════════════════════════
#  搜索状态缓存（用于编号下载和翻页）
# ══════════════════════════════════════════════════════════

_search_cache: dict[str, dict] = {}
"""
搜索结果缓存，key = f"{user_id}_{chat_id}"，value = {
    "query": 搜索关键词,
    "page":  当前页码,
    "results": [谱面列表],
    "total":  总结果数,
    "hasMore": 是否有更多页,
}
"""

def _get_cache_key(user_id: int, chat_id: int) -> str:
    return f"{user_id}_{chat_id}"


# ══════════════════════════════════════════════════════════
#  1. 生成搜索结果卡片图片（截图HTML）
# ══════════════════════════════════════════════════════════

async def _generate_tuf_search_card(
    results: list[dict],
    query: str,
    page: int,
    total: int,
    has_more: bool,
    output_filename: str = None,
) -> Optional[str]:
    """
    生成搜索结果列表的卡片图片（HTML → 截图）。
    """
    from modules.changelog import render_any_template, render_card_to_image

    # ── 构建结果列表 HTML ──────────────────────────────────
    results_html_parts = []
    start_num = (page - 1) * 10 + 1

    for i, level in enumerate(results):
        idx = start_num + i
        song = level.get("song", "?")
        artist = level.get("artist", "?")
        creator = level.get("creator", "?")
        if not creator:
            credits = level.get("levelCredits", [])
            creators = [c.get("creator", {}).get("name", "") for c in credits if c.get("role") == "charter"]
            creator = " | ".join(creators) if creators else "?"

        diff = level.get("difficulty", {})
        diff_name = diff.get("name", "?")
        diff_color = diff.get("color", "#888888")
        diff_icon = diff.get("icon", "")

        clears = level.get("clears", 0)
        tile_count = level.get("tileCount", 0)

        # 难度图标 HTML
        if diff_icon:
            diff_icon_html = (
                f'<div class="result-diff-icon has-image" '
                f'style="background:{diff_color}; background-image:url(\'{diff_icon}\'); '
                f'background-size:cover; background-position:center;">'
                f'<span class="result-diff-text"></span></div>'
            )
        else:
            diff_icon_html = (
                f'<div class="result-diff-icon" style="background:{diff_color};">'
                f'<span class="result-diff-text">{diff_name}</span></div>'
            )

        # Featured 标签
        featured_html = ""
        if level.get("isCurated"):
            featured_html = '<span class="result-featured">🌟 精选</span>'

        part = f'''
        <div class="result-item">
          {diff_icon_html}
          <div class="result-index">{idx}</div>
          <div class="result-info">
            <div class="result-song">{song} {featured_html}</div>
            <div class="result-meta">
              <span class="result-meta-item">🎤 {artist}</span>
              <span class="result-meta-item">🔧 {creator}</span>
              <span class="result-meta-item">✅ {clears} 通关</span>
              <span class="result-meta-item">🧱 {tile_count} 块</span>
            </div>
          </div>
        </div>
        '''
        results_html_parts.append(part)

    results_html = "\n".join(results_html_parts)

    # ── 分页信息 ──────────────────────────────────
    total_pages = (total + 9) // 10
    page_info = f"第 {page}/{total_pages} 页 · 共 {total} 个结果"

    page_hint = ""
    if has_more:
        page_hint = f"💡 输入 /~tufpage {page + 1} 查看下一页"
    elif page > 1:
        page_hint = f"💡 输入 /~tufpage {page - 1} 查看上一页"

    if not page_hint:
        page_hint = "💡 输入 /~tufd [编号] 下载谱面"

    # ── 填充模板 ──────────────────────────────────
    cfg = get_config()

    variables = {
        "QUERY": query,
        "PAGE": str(page),
        "TOTAL": str(total),
        "RESULTS_HTML": results_html,
        "PAGE_INFO": page_info,
        "PAGE_HINT": page_hint,
        "BRAND": f"Generated by {cfg.bot_name}",
    }

    full_html = render_any_template("tuf_search_results", variables)
    logger.info("[TUFSearch] 搜索结果模板填充完成: %d 条结果", len(results))

    # ── 截图 ──────────────────────────────────
    if not output_filename:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_filename = f"tuf_search_{ts}.png"

    return await render_card_to_image(full_html, output_filename, width=800)


# ══════════════════════════════════════════════════════════
#  2. 生成谱面详情卡片（增强版，含通关记录）
# ══════════════════════════════════════════════════════════

async def _generate_tuf_level_card(
    level_data: dict,
    output_filename: str = None,
    passes_data: list[dict] = None,
) -> Optional[str]:
    """
    从 TUF 谱面数据生成精美的谱面信息卡片图片。
    """
    from modules.changelog import render_any_template, render_card_to_image

    # ── 提取数据 ──────────────────────────────────
    song_name = level_data.get("song", "未知歌曲")
    artist_name = level_data.get("artist", "未知艺术家")
    creator_name = level_data.get("creator", "")
    if not creator_name:
        credits = level_data.get("levelCredits", [])
        creators = [c.get("creator", {}).get("name", "") for c in credits if c.get("role") == "charter"]
        creator_name = " | ".join(creators) if creators else "未知"

    # 难度信息
    diff = level_data.get("difficulty", {})
    diff_name = diff.get("name", "?")
    diff_color = diff.get("color", "#ffffff")
    diff_icon_url = diff.get("icon", "")

    # 统计信息
    duration_ms = level_data.get("levelLengthInMs")
    bpm = level_data.get("bpm")
    tile_count = level_data.get("tilecount") or level_data.get("tileCount")
    clears = level_data.get("clears", 0)
    downloads = level_data.get("downloadCount", 0) or level_data.get("downloads", 0)
    likes = level_data.get("likes", 0)
    level_id = level_data.get("id", 0)
    base_score = diff.get("baseScore", 0)
    old_id = level_data.get("oldId", "")

    duration_str = "⏱️ " + ("??:??" if not duration_ms else f"{int(duration_ms) // 60000}:{(int(duration_ms) // 1000) % 60:02d}")
    bpm_str = "?" if not bpm else str(int(bpm))
    tile_str = "?" if not tile_count else str(tile_count)
    clears_str = str(clears)
    downloads_str = str(downloads)
    likes_str = str(likes)

    # 下载链接
    dl_link = level_data.get("dlLink", "x")
    if dl_link == "x":
        dl_link = "#"

    # Featured & Verified 标签
    is_featured = level_data.get("isCurated", False)
    is_verified = level_data.get("isVerified", False)
    featured_tag = ""
    if is_featured:
        featured_tag += '<span class="tag-featured">🌟 精选</span>'
    if is_verified:
        featured_tag += ' <span class="tag-verified">✔ 已验证</span>'

    # 难度图标处理（使用 base64 嵌入）
    diff_icon_class = ""
    diff_icon_style = f"background: {diff_color};"

    if diff_icon_url:
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.get(diff_icon_url)
                if resp.status_code == 200:
                    img_base64 = base64.b64encode(resp.content).decode()
                    diff_icon_style = (
                        f"background: {diff_color}; "
                        f"background-image: url('data:image/png;base64,{img_base64}'); "
                        f"background-size: cover; background-position: center;"
                    )
                    diff_icon_class = "has-image"
                    diff_name = ""
        except Exception as e:
            logger.warning("[TUFCard] 下载难度图标失败: %s", e)

    # 评级信息
    rating = level_data.get("rating", {})
    rating_section = ""
    if rating:
        avg_diff = rating.get("averageDifficultyId")
        confirmed_at = rating.get("confirmedAt", "")
        if confirmed_at and len(confirmed_at) >= 10:
            confirmed_at = confirmed_at[:10]

        rating_section = f'''
        <div class="rating-section">
            <div class="rating-bar">
                <span class="rating-label">评级信息</span>
                <span class="rating-msg">
                    {"平均难度 ID: " + str(avg_diff) if avg_diff else ""}
                    {" · 确认于 " + confirmed_at if confirmed_at else ""}
                </span>
            </div>
        </div>
        '''

    # 通关记录（前5条）
    passes_section = ""
    if passes_data:
        passes_html_parts = []
        for j, p in enumerate(passes_data[:5], 1):
            player_name = p.get("player", {}).get("name", "?")
            speed = p.get("speed", 100)
            accuracy = p.get("accuracy")
            score_v2 = p.get("scoreV2")
            is_wf = p.get("isWorldsFirst", False)
            wf_badge = " 👑" if is_wf else ""

            # 安全类型转换（API 可能返回 None 或 float）
            try:
                speed_val = int(speed)
            except (ValueError, TypeError):
                speed_val = 100
            accuracy_val = float(accuracy) if accuracy is not None else 0.0
            score_v2_val = float(score_v2) if score_v2 is not None else 0.0

            passes_html_parts.append(
                f'<div class="pass-item">{j}. {player_name}{wf_badge} ({speed_val}%, {accuracy_val:.2f}%, {score_v2_val:.0f}pt)</div>'
            )

        passes_list_html = "\n".join(passes_html_parts)
        passes_section = f'''
        <div class="passes-section">
          <div class="passes-title">🏆 通关记录（前 5 位）</div>
          <div class="passes-list">
            {passes_list_html}
          </div>
          <div class="passes-more">[查看所有通关记录 →]</div>
        </div>
        '''

    # 别名
    aliases_section = ""
    song_aliases = level_data.get("songAliases", [])
    if song_aliases:
        aliases_html = " ".join([f"<span class='alias-tag'>{a}</span>" for a in song_aliases[:5]])
        aliases_section = f'''
        <div class="aliases-section">
          <div class="aliases-title">歌曲别名</div>
          <div class="aliases-list">{aliases_html}</div>
        </div>
        '''

    # 贡献者
    contributors_section = ""
    credits = level_data.get("levelCredits", [])
    if credits:
        contrib_parts = []
        role_map = {"charter": "谱师", "vfx": "特效师", "verifier": "验证者"}
        for c in credits[:5]:
            role = c.get("role", "?")
            name = c.get("creator", {}).get("name", "?")
            role_cn = role_map.get(role, role)
            contrib_parts.append(f"● {name} ({role_cn})")

        contribs_html = " ".join([f"<span class='contrib-item'>{c}</span>" for c in contrib_parts])
        contributors_section = f'''
        <div class="contributors-section">
          <div class="contributors-title">贡献者</div>
          <div class="contributors-list">{contribs_html}</div>
        </div>
        '''

    # 艺术家别名
    artist_aliases = level_data.get("artistAliases", [])
    artist_aliases_str = "、".join(artist_aliases) if artist_aliases else "无"

    # ── 填充模板 ──────────────────────────────────
    cfg = get_config()

    variables = {
        "DIFF_NAME": diff_name,
        "DIFF_ICON_CLASS": diff_icon_class,
        "DIFF_ICON_STYLE": diff_icon_style,
        "SONG_NAME": song_name,
        "SONG_NAME_CLASS": "song-name-long" if len(song_name) > 30 else "",
        "ARTIST_NAME": artist_name,
        "CREATOR_NAME": creator_name,
        "DURATION": duration_str,
        "BPM": bpm_str,
        "TILE_COUNT": tile_str,
        "CLEARS": clears_str,
        "DOWNLOADS": downloads_str,
        "LIKES": likes_str,
        "LEVEL_ID": str(level_id),
        "BASE_SCORE": str(base_score),
        "OLD_ID": str(old_id) if old_id else "无",
        "RATING_SECTION": rating_section,
        "PASSES_SECTION": passes_section,
        "ALIASES_SECTION": aliases_section,
        "CONTRIBUTORS_SECTION": contributors_section,
        "ARTIST_ALIASES": artist_aliases_str,
        "DL_LINK": dl_link,
        "FEATURED_TAG": featured_tag,
        "QUERY_TIME": datetime.now().strftime("%m-%d %H:%M"),
        "BRAND": f"Generated by {cfg.bot_name}",
    }

    full_html = render_any_template("tuf_level_card", variables)
    logger.info("[TUFCard] 模板填充完成: %s", song_name)

    # ── 截图 ──────────────────────────────────
    if not output_filename:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = re.sub(r'[^\w\s\-_\(\)\[\]\{\}]', '', song_name[:20]).strip()
        output_filename = f"tuf_{safe_name}_{ts}.png"

    return await render_card_to_image(full_html, output_filename, width=800)


async def _send_tuf_level_card(
    level_data: dict,
    group_id: Optional[int] = None,
    user_id: Optional[int] = None,
    is_group: bool = False,
    passes_data: list[dict] = None,
) -> str | None:
    """生成并发送 TUF 谱面卡片图片到聊天。"""
    from services.sender import send_group_msg, send_private_msg

    img_path = await _generate_tuf_level_card(level_data, passes_data=passes_data)
    if not img_path:
        logger.warning("[TUFCard] 生成失败，回退到纯文本模式")
        song_name = level_data.get("song", "?")
        artist = level_data.get("artist", "?")
        creator = level_data.get("creator", "?")
        if not creator:
            credits = level_data.get("levelCredits", [])
            creators = [c.get("creator", {}).get("name", "") for c in credits if c.get("role") == "charter"]
            creator = " | ".join(creators) if creators else "?"
        diff = level_data.get("difficulty", {}).get("name", "?")
        return f"🎵 **{song_name}**\n🎤 艺术家：{artist}\n🔧 作者：{creator}\n📊 难度：{diff}"

    normalized = img_path.replace("\\", "/")
    cq_msg = f"[CQ:image,file=file:///{normalized}]"

    target_id = group_id if is_group else user_id
    try:
        if is_group:
            await send_group_msg(cq_msg, target_id)
            logger.info("[TUFCard] 卡片已发送到群 %d", target_id)
        else:
            await send_private_msg(cq_msg, target_id)
            logger.info("[TUFCard] 卡片已发给用户 %d", target_id)
        return None
    except Exception as e:
        logger.error("[TUFCard] 发送卡片失败: %s", e, exc_info=True)
        return f"❌ 卡片发送失败: {e}"


# ══════════════════════════════════════════════════════════
#  3. 下载谱面文件
# ══════════════════════════════════════════════════════════

async def _download_tuf_level(level_data: dict, save_dir: Path) -> Optional[Path]:
    """
    下载 TUF 谱面文件到本地。
    """
    dl_link = level_data.get("dlLink", "x")
    if dl_link == "x":
        logger.warning("[TUFDownload] 该谱面无下载链接")
        return None

    song_name = level_data.get("song", "unknown")
    level_id = level_data.get("id", 0)

    safe_name = re.sub(r'[\\/*?:"<>|]', '', song_name)
    filename = f"{safe_name}_{level_id}.tuf"
    save_path = save_dir / filename

    logger.info("[TUFDownload] 下载谱面: %s → %s", dl_link[:60], filename)

    try:
        async with httpx.AsyncClient(timeout=60.0, follow_redirects=True) as client:
            resp = await client.get(dl_link)
            if resp.status_code != 200:
                logger.error("[TUFDownload] 下载失败 HTTP %d", resp.status_code)
                return None

            save_dir.mkdir(parents=True, exist_ok=True)
            with open(save_path, "wb") as f:
                f.write(resp.content)

            logger.info("[TUFDownload] 下载成功: %s (%d bytes)", filename, len(resp.content))
            return save_path

    except Exception as e:
        logger.error("[TUFDownload] 下载异常: %s", e, exc_info=True)
        return None


async def _send_tuf_file(file_path: Path, target_id: int, is_group: bool) -> bool:
    """发送 .tuf 文件到聊天。"""
    from services.sender import send_group_msg, send_private_msg

    normalized = str(file_path.resolve()).replace("\\", "/")
    filename = file_path.name

    cq_msg = f"[CQ:file,file=file:///{normalized},name={filename}]"

    try:
        if is_group:
            await send_group_msg(cq_msg, target_id)
        else:
            await send_private_msg(cq_msg, target_id)
        logger.info("[TUFFile] 文件已发送: %s → %d", filename, target_id)
        return True
    except Exception as e:
        logger.error("[TUFFile] 文件发送失败: %s", e, exc_info=True)
        return False


# ══════════════════════════════════════════════════════════
#  4. 命令处理函数
# ══════════════════════════════════════════════════════════

async def cmd_tuf_search(args, user_id, group_id, sender_name, is_group, bot_qq):
    """
    搜索 TUF 谱面，生成截图发送（带编号）。
    用法: /~tufsearch <关键词> [页码]
    """
    if not args:
        return "请输入搜索关键词，例如：/~tufsearch Camellia"

    # 解析参数：只有当参数个数 > 1 且最后一个是数字时，才分离出页码
    if len(args) > 1 and args[-1].isdigit():
        query = " ".join(args[:-1])
        page = int(args[-1])
    else:
        query = " ".join(args)
        page = 1

    chat_id = group_id if is_group else user_id
    cache_key = _get_cache_key(user_id, chat_id)

    logger.info("指令 /~tufsearch 触发 query=%s page=%d user=%d", query, page, user_id)

    # 搜索谱面
    from services.tuf_api import search_levels

    result = await search_levels(query, limit=10, page=page)

    if "error" in result:
        return f"❌ 搜索失败: {result['error']}"

    results = result.get("results", [])
    total = result.get("total", 0)
    has_more = result.get("hasMore", False)

    if not results:
        return f"😢 未找到谱面: {query}"

    # 存入缓存
    _search_cache[cache_key] = {
        "query": query,
        "page": page,
        "results": results,
        "total": total,
        "hasMore": has_more,
    }

    # 生成搜索结果截图
    async def _bg_send_search():
        from services.sender import send_group_msg, send_private_msg

        try:
            img_path = await _generate_tuf_search_card(
                results=results,
                query=query,
                page=page,
                total=total,
                has_more=has_more,
            )

            if not img_path:
                msg = f"❌ 搜索结果截图生成失败"
                if is_group:
                    await send_group_msg(msg, group_id)
                else:
                    await send_private_msg(msg, user_id)
                return

            normalized = img_path.replace("\\", "/")
            cq_msg = f"[CQ:image,file=file:///{normalized}]"

            if is_group:
                await send_group_msg(cq_msg, group_id)
            else:
                await send_private_msg(cq_msg, user_id)

            logger.info("[TUFSearch] 搜索结果截图已发送 → chat=%d", chat_id)

        except Exception as e:
            logger.error("[TUFSearch] 后台发送失败: %s", e, exc_info=True)

    asyncio.create_task(_bg_send_search())
    return None


async def cmd_tufd(args, user_id, group_id, sender_name, is_group, bot_qq):
    """
    通过编号下载搜索结果中的谱面。
    用法: /~tufd [编号]
    """
    if not args:
        return "请输入编号，例如：/~tufd 1"

    try:
        index = int(args[0])
    except ValueError:
        return "❌ 编号必须是数字，例如：/~tufd 1"

    chat_id = group_id if is_group else user_id
    cache_key = _get_cache_key(user_id, chat_id)

    if cache_key not in _search_cache:
        return "❌ 请先使用 /~tufsearch 搜索谱面"

    cache = _search_cache[cache_key]
    results = cache["results"]
    page = cache["page"]
    start_num = (page - 1) * 10 + 1

    # 检查编号是否有效
    if index < start_num or index >= start_num + len(results):
        return f"❌ 编号无效，当前页面编号范围：{start_num}~{start_num + len(results) - 1}"

    result_index = index - start_num
    level = results[result_index]
    slug = level.get("id", "")

    logger.info("指令 /~tufd 触发 index=%d slug=%s user=%d", index, slug, user_id)

    # 获取详情（需要下载链接）
    from services.tuf_api import get_level_by_slug

    level_data = await get_level_by_slug(slug)
    if not level_data:
        return f"❌ 获取谱面详情失败: {slug}"

    # 下载谱面文件
    dl_dir = Path("data/tuf_downloads")

    async def _bg_download():
        from services.sender import send_group_msg, send_private_msg

        try:
            file_path = await _download_tuf_level(level_data, dl_dir)
            if not file_path:
                msg = f"❌ 谱面下载失败，可能无下载链接"
                if is_group:
                    await send_group_msg(msg, group_id)
                else:
                    await send_private_msg(msg, user_id)
                return

            # 发送文件
            ok = await _send_tuf_file(file_path, chat_id, is_group)
            if not ok:
                msg = f"❌ 文件发送失败: {file_path.name}"
                if is_group:
                    await send_group_msg(msg, group_id)
                else:
                    await send_private_msg(msg, user_id)

        except Exception as e:
            logger.error("[TUFD] 后台下载失败: %s", e, exc_info=True)

    asyncio.create_task(_bg_download())
    return f"⏳ 正在下载谱面：{level.get('song', '?')}..."


async def cmd_tufpage(args, user_id, group_id, sender_name, is_group, bot_qq):
    """
    搜索结果翻页。
    用法: /~tufpage [页码]
    """
    if not args or not args[0].isdigit():
        return "请输入页码，例如：/~tufpage 2"

    page = int(args[0])

    chat_id = group_id if is_group else user_id
    cache_key = _get_cache_key(user_id, chat_id)

    if cache_key not in _search_cache:
        return "❌ 请先使用 /~tufsearch 搜索谱面"

    cache = _search_cache[cache_key]
    query = cache["query"]

    logger.info("指令 /~tufpage 触发 page=%d query=%s user=%d", page, query, user_id)

    # 搜索指定页码
    from services.tuf_api import search_levels

    result = await search_levels(query, limit=10, page=page)

    if "error" in result:
        return f"❌ 搜索失败: {result['error']}"

    results = result.get("results", [])
    total = result.get("total", 0)
    has_more = result.get("hasMore", False)

    if not results:
        return f"😢 第 {page} 页无结果"

    # 更新缓存
    _search_cache[cache_key] = {
        "query": query,
        "page": page,
        "results": results,
        "total": total,
        "hasMore": has_more,
    }

    # 生成截图并发送
    async def _bg_send_page():
        from services.sender import send_group_msg, send_private_msg

        try:
            img_path = await _generate_tuf_search_card(
                results=results,
                query=query,
                page=page,
                total=total,
                has_more=has_more,
            )

            if not img_path:
                msg = f"❌ 翻页截图生成失败"
                if is_group:
                    await send_group_msg(msg, group_id)
                else:
                    await send_private_msg(msg, user_id)
                return

            normalized = img_path.replace("\\", "/")
            cq_msg = f"[CQ:image,file=file:///{normalized}]"

            if is_group:
                await send_group_msg(cq_msg, group_id)
            else:
                await send_private_msg(cq_msg, user_id)

            logger.info("[TUFPage] 翻页截图已发送 → page=%d", page)

        except Exception as e:
            logger.error("[TUFPage] 后台发送失败: %s", e, exc_info=True)

    asyncio.create_task(_bg_send_page())
    return None


async def cmd_tuflevel(args, user_id, group_id, sender_name, is_group, bot_qq):
    """
    查询 TUF 谱面详情。
    用法: /~tuflevel <歌曲名|关卡ID>
    - 如果是数字，直接通过 TUF 关卡 ID 查询
    - 如果是字符串，搜索后取第一个结果
    """
    if not args:
        return "请输入歌曲名或关卡ID，例如：/~tuflevel Hello (BPM) 2021 或 /~tuflevel 5"

    query = " ".join(args)

    logger.info("指令 /~tuflevel 触发 query=%s user=%d", query, user_id)

    # 判断是否为纯数字（TUF 关卡 ID）
    if query.isdigit():
        level_id = int(query)
        from services.tuf_api import get_level_by_id

        level_data = await get_level_by_id(level_id)
        if not level_data:
            return f"❌ 未找到关卡 ID: {level_id}"
    else:
        # 搜索谱面
        from services.tuf_api import search_levels, get_level_by_slug

        result = await search_levels(query, limit=5)

        if "error" in result:
            return f"❌ 搜索失败: {result['error']}"

        results = result.get("results", [])
        if not results:
            return f"😢 未找到谱面: {query}"

        slug = results[0].get("id", "")
        level_data = await get_level_by_slug(slug)

        if not level_data:
            return f"❌ 获取谱面详情失败: {slug}"

    # 获取通关记录（前5条）
    from services.tuf_api import get_level_passes

    level_id = level_data.get("id", 0)
    passes_result = await get_level_passes(level_id, limit=5)
    passes_data = passes_result.get("passes", [])

    # 异步生成并发送卡片
    async def _bg_send_tuf():
        try:
            result = await _send_tuf_level_card(
                level_data,
                group_id=group_id if is_group else None,
                user_id=user_id if not is_group else None,
                is_group=is_group,
                passes_data=passes_data,
            )
            if result is not None:
                if is_group:
                    from services.sender import send_group_msg
                    await send_group_msg(result, group_id)
                else:
                    from services.sender import send_private_msg
                    await send_private_msg(result, user_id)
        except Exception as e:
            logger.error("[TUFLevel] 后台发送失败: %s", e, exc_info=True)

    asyncio.create_task(_bg_send_tuf())
    return None


# ══════════════════════════════════════════════════════════
#  别名命令
# ══════════════════════════════════════════════════════════

async def cmd_tuf_谱面(args, user_id, group_id, sender_name, is_group, bot_qq):
    """/~tuf谱面 <歌曲名|关卡ID> - 中文别名"""
    return await cmd_tuflevel(args, user_id, group_id, sender_name, is_group, bot_qq)
