"""
排行榜卡 —— Pillow 1:1 复刻 data/templates/leaderboard_card.html

复用 services/card_dark 基础层（深色赛博朋克主题）。
几何全部来自 Playwright 实测：card 408 宽 / head 71 / title-row 44 / entry 54 / foot 42.2
"""
from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageDraw

from services.card_dark import (
    C, BD, CARD_W, CARD_X, CARD_Y, WRAP_PT, WRAP_PB,
    TITLE_ROW_PT, TITLE_ROW_PX, TITLE_ROW_PB, TITLE_ROW_FS,
    LIST_PT, LIST_PX, LIST_PB, ENTRY_MB, RANK_W, VALUE_FS, NAME_FS,
    body_bg, glass_card, draw_head, draw_foot, draw_entry, entry_h, lh,
)
from services.card_base import cjk, mono, truncate, save_image


def build_payload(data: dict, bot_name: str = "幻梦") -> dict:
    """把 API 榜单数据整理成渲染载荷（与 build_leaderboard_html 同源）"""
    from services import wdsj_api as api

    board = data.get("board", {})
    return {
        "title": f"{board.get('group', '')} {board.get('displayName', '')}".strip(),
        "period": api.PERIOD_LABELS.get(data.get("type", "ALLTIME"), "总榜"),
        "unit": board.get("unit", ""),
        "entries": [
            {"rank": e.get("rank", i + 1), "name": e.get("owner", "?"),
             "value": f"{e.get('value', '')} {board.get('unit', '')}".strip()}
            for i, e in enumerate(data.get("entries", []) or [])
        ],
        "brand": f"Generated by {bot_name}",
    }


# 前 3 名的名次颜色（--gold / --silver / --bronze）
_RANK_COLORS = {1: C["gold"], 2: C["silver"], 3: C["bronze"]}


def render_leaderboard_card(payload: dict) -> Image.Image:
    """渲染排行榜卡（与 HTML 模板同数据、同外观）"""
    entries = payload.get("entries") or []

    # ── 高度 ──
    title_row_h = TITLE_ROW_PT + lh(TITLE_ROW_FS) + TITLE_ROW_PB
    eh = entry_h()
    list_h = LIST_PT + len(entries) * (eh + ENTRY_MB) + LIST_PB
    # ⚠️ 高度用 ceil 而非 round：浏览器截图对小数高度向上取整
    #    （实测 body 787.19px → 截图 788px）
    card_h = 71 + title_row_h + list_h + 42.2      # head + title-row + list + foot
    W = CARD_W + CARD_X * 2
    H = int(math.ceil(WRAP_PT + card_h + WRAP_PB))
    card_h_i = int(math.ceil(card_h))

    img = body_bg((W, H))
    glass_card(img, CARD_X, CARD_Y, CARD_W, card_h_i)
    d = ImageDraw.Draw(img)

    # ── .head ──
    draw_head(img, CARD_X, CARD_Y, CARD_W,
              logo_text="LB", title_nm="幻梦", title_tp="LEADERBOARD",
              tag=str(payload.get("period") or "总榜"), sep_sl="/")
    y = CARD_Y + 71

    # ── .title-row ──
    ty = y + TITLE_ROW_PT + lh(TITLE_ROW_FS) / 2
    d.text((CARD_X + TITLE_ROW_PX, ty),
           truncate(d, str(payload.get("title") or ""), cjk(TITLE_ROW_FS, bold=True),
                    CARD_W - TITLE_ROW_PX * 2),
           font=cjk(TITLE_ROW_FS, bold=True), fill=C["text"], anchor="lm")
    y += title_row_h

    # ── .list ──
    ly = y + LIST_PT
    for e in entries:
        rk = e.get("rank") or 1
        draw_entry(img, CARD_X + LIST_PX, ly, CARD_W - LIST_PX * 2,
                   rank=f"#{rk}", name=str(e.get("name") or "?"),
                   value=str(e.get("value") or ""),
                   rank_color=_RANK_COLORS.get(rk))
        ly += eh + ENTRY_MB

    # ── .foot ──
    draw_foot(img, CARD_X, CARD_Y + card_h_i - int(round(42.2)), CARD_W,
              left="", left_brand="幻梦 Bot", right="HUANMENG")
    return img


def save_leaderboard_card(data: dict, out_path, bot_name: str = "幻梦") -> Path:
    """渲染排行榜卡并保存（bot 走这条）"""
    # 按扩展名输出（原模板文件名是 .png）
    return save_image(render_leaderboard_card(build_payload(data, bot_name)),
                      out_path, 95)
