# -*- coding: utf-8 -*-
"""KOOK bg_tasks 补位公告补丁（用完即删）"""
import io

PATH = "/root/kook_bot/plugins/bg_tasks/main.py"
src = io.open(PATH, encoding="utf-8").read()

anchor = '''                            logger.info("日榜已推送: %d 人 (%s)", len(rows), today)
                except Exception as e:
                    logger.warning("日榜推送失败: %s", e)'''
assert src.count(anchor) == 1, src.count(anchor)

notice = '''                            logger.info("日榜已推送: %d 人 (%s)", len(rows), today)
                    else:
                        # ★ v2.3.81: 数据缺失（停机导致基线快照缺失）→ 补位公告卡替代日报
                        try:
                            _bn = get_config().bot_name or "幻梦Bot"
                            notice_html = (
                                '<div style="width:540px;padding:24px;font-family:PingFang SC,Microsoft YaHei,sans-serif;'
                                'background:linear-gradient(160deg,#fdf4ec,#f3eff2);border-radius:20px;color:#3a332c;">'
                                '<div style="font-size:19px;font-weight:800;">服务器异常 · 战绩日报未产出</div>'
                                '<div style="font-size:12.5px;color:#8a7f76;margin:6px 0 12px;">' + today + ' · 日榜数据缺失说明</div>'
                                '<div style="font-size:13px;line-height:1.9;">服务器异常停机，当日战绩增量未采集，日榜无法统计。<br>'
                                '次日 0:01 起正常产出，无需任何操作。</div>'
                                '<div style="font-size:11px;color:#a2958a;margin-top:14px;">补位公告 · Generated by ' + _bn + '</div>'
                                '</div>')
                            png_path = await self.ctx.card.render_html(
                                notice_html, width=540, height=400, wait_ms=500, timeout_ms=10000)
                            if png_path:
                                cq = f"[img:file:{png_path}]"
                                cfg = get_config()
                                gids = cfg.config.get("wdsj", {}).get("target_groups", []) if hasattr(cfg, 'config') else []
                                if not gids:
                                    gids = cfg.group_ids()
                                for gid in gids:
                                    try:
                                        await self.ctx.message.send(cq, int(gid), True)
                                    except Exception:
                                        pass
                                logger.info("日榜数据缺失，已推送补位公告卡")
                        except Exception as _e2:
                            logger.warning("补位公告卡推送失败: %s", _e2)
                except Exception as e:
                    logger.warning("日榜推送失败: %s", e)'''

src = src.replace(anchor, notice, 1)
io.open(PATH, "w", encoding="utf-8", newline="\n").write(src)
print("kook bg_tasks patched")
