# -*- coding: utf-8 -*-
"""发一次"服务器异常"补位公告卡（用完即删）"""
import asyncio
import os
import sys
import time

sys.path.insert(0, "/root/bot")
os.chdir("/root/bot")

HTML = """<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8">
<style>
*{box-sizing:border-box;margin:0;padding:0}
html,body{width:640px;font-family:"PingFang SC","Microsoft YaHei","Noto Sans CJK SC",sans-serif;
  -webkit-font-smoothing:antialiased;}
.card{width:640px;padding:36px 40px 30px;
  background:
    radial-gradient(620px 300px at 10% -6%, rgba(255,183,154,.34), transparent 60%),
    radial-gradient(620px 300px at 92% -6%, rgba(158,188,255,.36), transparent 60%),
    linear-gradient(160deg,#fbf6f0 0%,#f4f0ec 42%,#eef1f6 100%);
  border-radius:30px;position:relative;overflow:hidden;color:#3a332c;}
.card::before{content:"";position:absolute;inset:0;pointer-events:none;
  background-image:url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="140" height="140"><circle cx="8" cy="8" r="1" fill="white" opacity="0.5"/></svg>');
  opacity:.5;}
.wrap{position:relative;z-index:2;display:flex;flex-direction:column;gap:14px;}
:root{--muted:#8a7f76;--accent:#f0875c;}
.top{display:flex;align-items:center;gap:14px;}
.badge{width:52px;height:52px;border-radius:16px;display:grid;place-items:center;
  background:linear-gradient(135deg,#ffb37a,#f0875c);box-shadow:0 8px 18px rgba(230,120,58,.3);}
.badge span{font-size:26px;font-weight:900;color:#fff;}
.brand{font-size:21px;font-weight:800;}
.brand i{font-style:normal;font-size:12.5px;color:var(--muted);font-weight:400;margin-left:8px;}
.main{background:rgba(255,255,255,.62);backdrop-filter:blur(14px);
  border:1px solid rgba(255,255,255,.9);border-radius:18px;padding:16px 20px;
  box-shadow:0 8px 20px rgba(120,80,60,.08);}
.main .line{font-size:14px;line-height:1.9;color:#3a332c;}
.main .line b{color:#c96a42;}
.panel{background:rgba(255,255,255,.55);backdrop-filter:blur(18px);
  border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:15px 18px;
  box-shadow:0 10px 24px rgba(120,80,60,.07), inset 0 1px 0 rgba(255,255,255,.9);}
.k{font-size:11.5px;letter-spacing:.2em;color:var(--muted);margin-bottom:9px;font-weight:700;}
.row{display:flex;gap:10px;padding:4.5px 0;font-size:13px;align-items:baseline;}
.row + .row{border-top:1px solid rgba(150,130,110,.12);}
.row .d{flex:0 0 150px;color:var(--muted);}
.row .v{color:#3a332c;}
.foot{display:flex;align-items:center;gap:9px;font-size:10.5px;color:var(--muted);padding:0 4px;}
.pill{padding:3px 12px;border-radius:999px;background:rgba(255,255,255,.75);
  border:1px solid rgba(255,255,255,.9);color:var(--muted);font-weight:700;}
</style></head>
<body>
<div class="card">
  <div class="wrap">
    <div class="top">
      <div class="badge"><span>!</span></div>
      <div class="brand">起床战争日榜 · 服务器异常公告</div>
    </div>
    <div class="main">
      <div class="line">服务器于 <b>10-06 晚间异常停机</b>，<b>10-07 21:45 恢复</b>。</div>
      <div class="line">期间战绩采集与日榜产出中断，<b>今日（10-07）日榜数据缺失</b>，特此说明。</div>
    </div>
    <div class="panel">
      <div class="k">影响范围 IMPACT</div>
      <div class="row"><span class="d">停机时段</span><span class="v">10-06 ~21:00 → 10-07 21:45</span></div>
      <div class="row"><span class="d">缺失轮次</span><span class="v">0:01 / 4:01 / 8:01 / 12:01 / 16:01 / 20:01（共 6 轮）</span></div>
      <div class="row"><span class="d">数据范围</span><span class="v">10-06 晚间 → 10-07 全天的战绩增量未采集</span></div>
      <div class="row"><span class="d">恢复时间</span><span class="v">明天 0:01 起正常产出，无需任何操作</span></div>
    </div>
    <div class="foot">
      <span class="pill">补位公告</span><span>此卡替代今日日榜 · 明日恢复正常</span>
      <span style="flex:1"></span><span>Generated by 幻梦bot</span>
    </div>
  </div>
</div>
</body></html>"""


async def main():
    from modules.changelog import _ensure_browser
    from services.sender import send_group_msg
    browser = await _ensure_browser()
    page = await browser.new_page(viewport={"width": 640, "height": 100})
    await page.set_content(HTML)
    await page.wait_for_timeout(500)
    await page.set_viewport_size({"width": 640, "height": 100})
    out = f"/root/bot/data/img_temp/wdsj_daily_notice_{int(time.time())}.png"
    await page.screenshot(path=out, full_page=True)
    await page.close()
    cq = f"[CQ:image,file=file:///{out}]"
    await send_group_msg(cq, 1058782600)
    print("sent:", out, os.path.getsize(out), "bytes")


asyncio.run(main())
